name: Security Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code\
        uses: actions/checkout@v5 # v4.2.2
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3 # v3.27.9
        with:
          languages: actions

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3 # v3.27.9
