name: Security Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codeql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@df409f7d9260372694d2637f0b99e74207220ba7 # v3.27.9
        with:
          languages: javascript, python
          queries: security-extended

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@df409f7d9260372694d2637f0b99e74207220ba7 # v3.27.9
